#!/bin/bash
cd ./$(git rev-parse --show-cdup)
utilities/allmake
cd test_binaries
rm -rf *.output
rm -rf *.executed
touch .mid_binary
chmod u+rw .mid_binary
ESC=$(printf '\033')
for file in $(ls *.s)
do
    binname=${file:0:${#file}-2}
    echo "[TEST] "$binname".s ..."
    echo "assembling "$binname".s ..."
    echo -n "${ESC}[31m"
    ../assembler/asm $binname".s" $binname
    echo -n "${ESC}[m"
    echo "simulating "$binname" ..."
    touch $binname".input"
    echo "${ESC}[31m"
    ../simulator/sim $binname -auto -ifnc   >"$binname.executed"
    echo "${ESC}[m"
    sed  -i .bak s/"${ESC}\[[0-9]*m"//g $binname".executed"
    echo ""
done