#!/bin/bash
cd ./$(git rev-parse --show-cdup)
utilities/allmake
cd test_binaries
rm -rf *.output
rm -rf *.executed

ESC=$(printf '\033')
ARC=$(uname -m)
if [ ${ARC} = "arm64" ]; then
    echo "a"
    sed_option=".bak"
fi
for file in $(ls *.s)
do
    binname=${file:0:${#file}-2}
    echo "[TEST] "$binname".s ..."
    echo "assembling "$binname".s ..."
    echo -n "${ESC}[31m"
    ../assembler/asm $binname".s" $binname
    echo -n "${ESC}[m"
    echo "simulating "$binname" ..."
    touch $binname".input"
    echo "${ESC}[31m"
    ../simulator/sim $binname -auto -ifnc   >"$binname.executed"
    echo "${ESC}[m"
    sed  -i $sed_option s/"${ESC}\[[0-9]*m"//g $binname".executed"
    echo ""
done